
POST http://localhost:3000/api/v1/users/register
content-type: application/json

{
    
  "firstName": "Pasang",
  "lastName": "Sherpa",
  "email": "pasang@gmail.com",
  "gender": "male",
  "password": "pasang",
  "cpassword": "pasang",
  "isAdmin": true
}

###

POST http://localhost:3000/api/v1/users/localLogin
content-type: application/json

{
  "email": "madan@gmail.com",
  "password": "test3"
  }
  

###

GET http://localhost:3000/api/v1/books


###
POST http://localhost:3000/api/v1/books
content-type: application/json

{
   "title": "mohko",
    "description": "mohko",
    "ISBN": "mohko",
    "publisher": "mohko"
}



